### ISSUE TITLE
Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.

### ISSUE THREAD

**Issue by AlexPeret** [dotnet-websharper/aspnetcore#9]
hi!

I'm testing an existing client-server application on .NET Core 3 and it throws the following exception during request:

```
Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
System.InvalidOperationException: Synchronous operations are disallowed. Call WriteAsync or set AllowSynchronousIO to true instead.
   at Microsoft.AspNetCore.Server.IIS.Core.HttpResponseStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.TextWriter.Dispose()
   at <StartupCode$WebSharper-UI>.$Doc.Server.Page@43-1.Invoke(Stream s)
   at WebSharper.AspNetCore.Sitelets.writeResponse@28.Invoke(Task`1 t)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

The quick fix for me was to set the server AllowSynchronousIO option, which [default's value is false now](https://github.com/aspnet/AspNetCore/issues/7644):

```
    member this.ConfigureServices(services: IServiceCollection) =
        services.Configure<KestrelServerOptions>(fun (options:KestrelServerOptions) ->
            options.AllowSynchronousIO <- true
        )
        |> ignore

        services.Configure<IISServerOptions>(fun (options:IISServerOptions) -> 
            options.AllowSynchronousIO <- true
        )
        |> ignore

        // services.AddSitelet(Site.Main)
        services.AddSitelet<Site>()
            .AddAuthentication("WebSharper")
            .AddCookie("WebSharper", fun options -> ())
        |> ignore

```

Thanks,
Alex

**Comment by Jand42** [comment]
Sorry for the late reply: fixed in 7ba0b221c14095c74277badb6dd3e8899f76d436, released in version 4.6.0.120
